# Generated by Django 5.0.6 on 2024-08-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_feature_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='feature_image',
            new_name='featured_image',
        ),
        migrations.AddField(
            model_name='project',
            name='vote_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
