name: Django Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_DB: devdb
          POSTGRES_USER: devuser
          POSTGRES_PASSWORD: changeme
        ports:
          - 5432:5432
        options: > 
          --health-cmd="pg_isready -U devuser -d devdb" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and run the Docker containers
      run: |
        docker-compose -f docker-compose.yml up --build -d
        docker-compose exec app sh -c "python manage.py migrate"
      
    - name: Run tests
      run: |
        docker-compose exec app sh -c "python manage.py test"

    - name: Run Flake8 linting
      run: |
        docker-compose exec app sh -c "flake8 ."
